//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopHelper_v0._0.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class RolesForSpecificForm : global::System.Configuration.ApplicationSettingsBase {
        
        private static RolesForSpecificForm defaultInstance = ((RolesForSpecificForm)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new RolesForSpecificForm())));
        
        public static RolesForSpecificForm Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Main {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Main"]));
            }
            set {
                this["Main"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Admin</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Admin {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Admin"]));
            }
            set {
                this["Admin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>Admin</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection Manager {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Manager"]));
            }
            set {
                this["Manager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection POS {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["POS"]));
            }
            set {
                this["POS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection Reports {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["Reports"]));
            }
            set {
                this["Reports"] = value;
            }
        }
    }
}
